import { Settings, ThemeDefinition, RangeDefinition, IdentityDefinition } from './types';

export const STORAGE_KEY = 'linux-sb-wide-layout-settings-v2';

export const SETTINGS_VERSION = 6;

// 内置图床预设
export const IMGUR_PRESET = {
    provider: 'imgur',
    host: 'https://imgur.com/',
    endpoint: 'https://api.imgur.com/3/image',
    field: 'image',
    responsePath: 'data.link',
    authMode: 'imgur-client-id',
    token: ''
};

export const CATBOX_PRESET = {
    provider: 'catbox',
    host: 'https://catbox.moe/',
    endpoint: 'https://catbox.moe/user/api.php',
    field: 'fileToUpload',
    responsePath: '',
    authMode: 'none',
    token: ''
};

// Postimages：免密钥、文件永久、浏览器 fetch 可直接跨域上传（其自身网页端即用 fetch 直传）
export const POSTIMAGES_PRESET = {
    provider: 'postimages',
    host: 'https://postimages.org/',
    endpoint: 'https://postimages.org/json',
    field: 'upfile',
    responsePath: '',
    authMode: 'none',
    token: ''
};

// FreeImage.Host：免注册，官方文档公开了可用的 API key；响应 JSON 中 image.url 即直链
export const FREEIMAGE_PRESET = {
    provider: 'freeimage',
    host: 'https://freeimage.host/',
    endpoint: 'https://freeimage.host/api/1/upload',
    field: 'source',
    responsePath: 'image.url',
    authMode: 'none',
    token: '',
    key: '6d207e02198a847aa98d0a2a901485a5'
};

export const DEFAULTS: Settings = {
    version: SETTINGS_VERSION,
    maxWidth: 1100,
    headerHeight: 68,
    fontSize: 15,
    radius: 6,
    sidebarWidth: 270,
    shellPadding: 28,
    columnGap: 28,
    theme: 'neutral',
    accent: '#b8b8b8',
    textPalette: 'neutral',
    textColor: '#eeeeee',
    homePersonalized: false,
    homePostNewWindow: false,
    realtimeRefresh: false,
    realtimeRefreshInterval: 60,
    sidebarSwap: false,
    identityBadges: true,
    uidBadges: true,
    avatarProfileCard: true,
    autoCheckin: false,
    autoCheckinLastDate: '',
    imageLightbox: false,
    imageUpload: false,
    imageUploadProvider: 'freeimage',
    imageUploadHost: FREEIMAGE_PRESET.host,
    imageUploadEndpoint: FREEIMAGE_PRESET.endpoint,
    imageUploadFileField: FREEIMAGE_PRESET.field,
    imageUploadResponsePath: FREEIMAGE_PRESET.responsePath,
    imageUploadAuthMode: FREEIMAGE_PRESET.authMode,
    imageUploadToken: '',
    imageUploadSettingsCollapsed: false,
    imageUploadProfiles: [],
    imageUploadActiveProfileId: '',
    panelLeft: null,
    panelTop: null,
    toggleLeft: null,
    toggleTop: null,
    titleFilters: [],
    userFilters: []
};

export const NODEIMAGE_PRESET = {
    provider: 'nodeimage',
    host: 'https://nodeimage.com/',
    endpoint: 'https://api.nodeimage.com/api/upload',
    field: 'image',
    responsePath: 'data.url',
    authMode: 'nodeimage-api-key',
    token: ''
};

export const TEXT_PALETTES: { [key: string]: { label: string; color: string } } = {
    neutral: { label: '中性银白', color: '#eeeeee' },
    mist: { label: '雾灰', color: '#d6d6d6' },
    silver: { label: '柔银', color: '#c7c7c7' },
    warm: { label: '暖白', color: '#eee9e1' },
    custom: { label: '自定义颜色', color: '#eeeeee' }
};

/*
 * 身份标识扩展位：如站点新增公开身份，只需在此对象追加条目。
 * key 用于样式识别；label 为显示名称；aliases 填写个人页 .user-rank 中可能出现的原始身份文案。
 * 不要在页面 DOM 中硬编码 UID 或用户名，身份始终以公开个人页返回的数据为准。
 */
export const IDENTITY_DEFINITIONS: { [key: string]: IdentityDefinition } = {
    creator: { label: '创作者', aliases: ['创作者'] },
    aiRobot: { label: 'AI机器人', aliases: ['AI机器人', 'AI 机器人'] },
    communityHost: { label: '社区主理人', aliases: ['社区主理人'] }
    // 示例：newRole: { label: '新身份', aliases: ['站点实际身份文案'] }
};

export const HOME_PROFILE_CACHE_TTL = 10 * 60 * 1000;
export const HOME_PRIVATE_DATA_CACHE_TTL = 60 * 1000;

export const HOME_LOGO_SVG = [
    '<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="LINUX SB logo">',
    '<circle fill="#EFEFEF" cx="256" cy="256" r="256"/>',
    '<path d="M279.69124,269.784594 C289.092146,253.471257 283.562201,232.595717 267.248865,223.194811 C250.935529,213.793906 230.059989,219.32385 220.659083,235.637186 L212.087669,250.429788 C202.686764,266.743124 208.216708,287.618664 224.530044,297.01957 C240.84338,306.420476 261.718921,300.890531 271.119826,284.577195 L279.69124,269.784594 Z" fill="#737373"/>',
    '<path d="M298.6313,68.356366 C308.032206,52.04303 302.502261,31.1674897 286.188925,21.7665841 C269.875589,12.3656785 249.000048,17.895623 239.599143,34.208959 L145.866584,196.651078 C136.465678,212.964414 141.995623,233.839955 158.308959,243.24086 C174.622295,252.641766 195.497836,247.111821 204.898741,230.798485 L298.6313,68.356366 Z" fill="#1E1E20"/>',
    '<path d="M355.419725,307.249829 C364.82523,290.910346 359.29258,270.001346 342.971263,260.585373 C326.649946,251.1694 305.764193,256.708207 296.358689,273.047691 L202.580275,435.750171 C193.17477,452.089654 198.70742,472.998654 215.028737,482.414627 C231.350054,491.8306 252.235807,486.291793 261.641311,469.952309 L355.419725,307.249829 Z" fill="#FEB005"/>',
    '</svg>'
].join('');

export const RANGE_DEFINITIONS: RangeDefinition[] = [
    { key: 'maxWidth', label: '页面最大宽度', min: 960, max: 2200, step: 20, unit: 'px' },
    { key: 'headerHeight', label: '顶部栏高度', min: 48, max: 100, step: 2, unit: 'px' },
    { key: 'fontSize', label: '正文基准字号', min: 13, max: 22, step: 1, unit: 'px' },
    { key: 'radius', label: '全局圆角', min: 0, max: 14, step: 1, unit: 'px' },
    { key: 'sidebarWidth', label: '侧栏宽度', min: 220, max: 420, step: 10, unit: 'px' },
    { key: 'shellPadding', label: '内容内边距', min: 12, max: 56, step: 2, unit: 'px' },
    { key: 'columnGap', label: '正文与侧栏间距', min: 12, max: 56, step: 2, unit: 'px' }
];

/*
 * 默认中性深灰严格使用中性灰阶作为界面底色。
 * 彩色只用于成功、警告、错误等语义反馈，避免背景偏蓝或偏紫。
 */
export const THEMES: { [key: string]: ThemeDefinition } = {
    neutral: {
        label: '中性深灰（默认）',
        accent: '#b8b8b8',
        textColor: '#eeeeee',
        vars: {
            '--bg': '#121212',
            '--panel': '#1b1b1b',
            '--line': '#343434',
            '--line-soft': '#272727',
            '--text': '#eeeeee',
            '--text-muted': '#b6b6b6',
            '--text-subtle': '#898989',
            '--text-disabled': '#666666',
            '--success': '#9fbea9',
            '--success-soft': '#223128',
            '--danger': '#e28b8b',
            '--danger-soft': '#3a2424',
            '--warning': '#d8b276',
            '--warning-soft': '#382e20',
            '--info': '#9bb4d0',
            '--info-soft': '#25303b',
            '--inverse': '#090909',
            '--inverse-border': '#3a3a3a',
            '--inverse-text': '#f5f5f5',
            '--color-dark-rgb': '0,0,0',
            '--backdrop': 'rgba(0,0,0,.68)',
            '--shadow-base': 'rgba(0,0,0,.28)',
            '--shadow-medium': 'rgba(0,0,0,.48)'
        }
    },
    graphite: {
        label: '石墨青',
        accent: '#7faea6',
        textColor: '#ecf0f2',
        vars: {
            '--bg': '#111416',
            '--panel': '#191d20',
            '--line': '#30363b',
            '--line-soft': '#24292d',
            '--text': '#ecf0f2',
            '--text-muted': '#a9b1b7',
            '--text-subtle': '#77818a',
            '--text-disabled': '#5f686f',
            '--success': '#8bb59b',
            '--success-soft': '#203329',
            '--danger': '#df8888',
            '--danger-soft': '#382326',
            '--warning': '#d2ab70',
            '--warning-soft': '#362d20',
            '--info': '#8fafd0',
            '--info-soft': '#24303c',
            '--inverse': '#090b0c',
            '--inverse-border': '#343b40',
            '--inverse-text': '#f4f7f8',
            '--color-dark-rgb': '3,5,6',
            '--backdrop': 'rgba(3,5,6,.68)',
            '--shadow-base': 'rgba(0,0,0,.30)',
            '--shadow-medium': 'rgba(0,0,0,.50)'
        }
    },
    warm: {
        label: '暖石墨',
        accent: '#b8a27f',
        textColor: '#eee9e1',
        vars: {
            '--bg': '#151310',
            '--panel': '#1e1b17',
            '--line': '#37322b',
            '--line-soft': '#29251f',
            '--text': '#eee9e1',
            '--text-muted': '#b8afa3',
            '--text-subtle': '#8b8277',
            '--text-disabled': '#685f55',
            '--success': '#a3b68e',
            '--success-soft': '#293022',
            '--danger': '#df8e84',
            '--danger-soft': '#3a2521',
            '--warning': '#d4ad70',
            '--warning-soft': '#392f20',
            '--info': '#99adc2',
            '--info-soft': '#283039',
            '--inverse': '#0b0a08',
            '--inverse-border': '#3b362f',
            '--inverse-text': '#f7f3ec',
            '--color-dark-rgb': '5,4,3',
            '--backdrop': 'rgba(5,4,3,.68)',
            '--shadow-base': 'rgba(0,0,0,.28)',
            '--shadow-medium': 'rgba(0,0,0,.48)'
        }
    },
    original: {
        label: '跟随原站主题',
        accent: '#5eaaa0',
        textColor: '#c8c9d9',
        vars: null
    }
};

export const THEME_VARIABLES = [
    '--bg', '--panel', '--line', '--line-soft',
    '--text', '--text-muted', '--text-subtle', '--text-disabled',
    '--brand', '--brand-hover', '--brand-soft',
    '--success', '--success-soft', '--danger', '--danger-soft',
    '--warning', '--warning-soft', '--info', '--info-soft',
    '--inverse', '--inverse-border', '--inverse-text',
    '--color-dark-rgb', '--backdrop', '--shadow-base', '--shadow-medium',
    '--focus-ring', '--swal2-background', '--swal2-color',
    '--swal2-validation-message-background', '--swal2-validation-message-color'
];

export const BASE_CSS = [
    '@media (min-width: 721px) {',
    '  :root {',
    '    --font-size-sm: calc(var(--lsb-base-font-size) - 2px) !important;',
    '    --font-size-md: var(--lsb-base-font-size) !important;',
    '    --font-size-lg: calc(var(--lsb-base-font-size) + 1px) !important;',
    '  }',
    '  body { font-size: var(--lsb-base-font-size) !important; }',
    '  .top .bar {',
    '    width: min(var(--lsb-wide-max), calc(100vw - 48px)) !important;',
    '    max-width: none !important;',
    '    min-height: var(--lsb-header-height) !important;',
    '    padding: 0 20px !important;',
    '    grid-template-rows: var(--lsb-header-height) !important;',
    '    column-gap: 16px !important;',
    '  }',
    '  .top .brand { font-size: var(--lsb-base-font-size) !important; }',
    '  .top .brand::before { width: 28px !important; height: 28px !important; flex-basis: 28px !important; }',
    '  .top .search-form { width: 280px !important; height: 36px !important; }',
    '  main.wrap, .footer, .forum-more-panel {',
    '    width: min(var(--lsb-wide-max), calc(100vw - 48px)) !important;',
    '    max-width: none !important;',
    '  }',
    '  main.wrap { padding: 18px 0 28px !important; }',
    '  .home-shell { padding: var(--lsb-shell-padding) !important; }',
    '  .home-shell .forum-layout, .forum-layout { gap: var(--lsb-column-gap) !important; }',
    '  .home-shell .forum-layout {',
    '    display: grid !important; grid-template-columns: minmax(0, 1fr) var(--lsb-sidebar-width) !important;',
    '    align-items: start !important;',
    '  }',
    '  .home-shell .forum-main { grid-column: 1 !important; grid-row: 1 !important; }',
    '  .home-shell .sidebar { grid-column: 2 !important; grid-row: 1 !important; }',
    '  .home-shell .forum-layout.lsb-home-sidebar-swapped {',
    '    grid-template-columns: var(--lsb-sidebar-width) minmax(0, 1fr) !important;',
    '  }',
    '  .home-shell .forum-layout.lsb-home-sidebar-swapped > .forum-main { grid-column: 2 !important; grid-row: 1 !important; }',
    '  .home-shell .forum-layout.lsb-home-sidebar-swapped > .sidebar { grid-column: 1 !important; grid-row: 1 !important; }',
    '  .home-shell .forum-layout.lsb-home-personalized-layout { row-gap: 0 !important; }',
    '  .home-shell .forum-layout.lsb-home-personalized-layout > #lsb-home-personalization {',
    '    grid-column: 1 / -1 !important; grid-row: 1 !important; min-width: 0; width: 100%; box-sizing: border-box;',
    '  }',
    '  .home-shell .forum-layout.lsb-home-personalized-layout > .forum-main { grid-column: 1 !important; grid-row: 2 !important; }',
    '  .home-shell .forum-layout.lsb-home-personalized-layout > .sidebar { grid-column: 2 !important; grid-row: 2 !important; }',
    '  .home-shell .forum-layout.lsb-home-personalized-layout.lsb-home-sidebar-swapped > .forum-main { grid-column: 2 !important; grid-row: 2 !important; }',
    '  .home-shell .forum-layout.lsb-home-personalized-layout.lsb-home-sidebar-swapped > .sidebar { grid-column: 1 !important; grid-row: 2 !important; }',
    '  .sidebar { width: var(--lsb-sidebar-width) !important; }',
    '  /* 版块列表持续常驻：拉伸其所在侧栏至主内容高度，避免 sticky 在侧栏内容末尾提前停止。 */',
    '  @supports selector(.forum-layout:has(> .sidebar > .forum-enhancements-sidebar-card)) {',
    '    .forum-layout:has(> .sidebar > .forum-enhancements-sidebar-card) > .sidebar { align-self: stretch !important; }',
    '    .forum-layout:has(> .sidebar > .forum-enhancements-sidebar-card) > .sidebar > .forum-enhancements-sidebar-card {',
    '      position: sticky !important; top: 12px; z-index: 2; align-self: flex-start;',
    '      max-height: calc(100vh - 12px - 240px); overflow-y: auto; overscroll-behavior: contain; scrollbar-gutter: stable;',
    '    }',
    '    .forum-layout:has(> .sidebar > .forum-enhancements-sidebar-card) > .sidebar > .forum-enhancements-sidebar-card .forum-enhancements-sidebar-list { min-width: 0; }',
    '  }',
    '  .post-item { min-height: 64px !important; padding-top: 13px !important; padding-bottom: 13px !important; }',
    '  .post-title, .post-content, .notification-content { font-size: var(--lsb-base-font-size) !important; }',
    '  .post-content { line-height: 1.75 !important; }',
    '  .post-meta, .topic-pages, .post-content-stats, .profile-exit small {',
    '    font-size: calc(var(--lsb-base-font-size) - 2px) !important;',
    '  }',
    '  h2 { font-size: calc(var(--lsb-base-font-size) + 3px) !important; }',
    '  h3 { font-size: calc(var(--lsb-base-font-size) + 1px) !important; }',
    '}',
    '@media (min-width: 721px) and (max-width: 1180px) {',
    '  .top .bar, main.wrap, .footer, .forum-more-panel { width: calc(100vw - 24px) !important; }',
    '}',
    '#lsb-home-personalization {',
    '  display: grid; justify-items: center; gap: 0; padding: 42px 20px 38px;',
    '  margin: -4px 0 20px; border-bottom: 1px solid var(--line-soft); text-align: center;',
    '}',
    '#lsb-home-personalization .lsb-home-logo {',
    '  display: block; width: clamp(64px, 7vw, 96px); height: auto; margin: 0 0 14px;',
    '  filter: drop-shadow(0 12px 24px rgba(0,0,0,.24));',
    '}',
    '#lsb-home-personalization .lsb-home-tagline {',
    '  margin: 0; color: var(--text); font-size: clamp(18px, 2.1vw, 28px);',
    '  font-weight: 700; letter-spacing: .08em; line-height: 1.25;',
    '}',
    '#lsb-home-personalization .lsb-home-search-form {',
    '  grid-column: auto; grid-row: auto; justify-self: center; display: flex;',
    '  width: min(720px, 100%); height: 46px; margin: 24px auto 0;',
    '  border: 1px solid var(--line); border-radius: var(--radius);',
    '  background: var(--panel); box-shadow: 0 10px 28px var(--shadow-base);',
    '}',
    '#lsb-home-personalization .lsb-home-search-form .search-input { font-size: var(--font-size-md); }',
    '#lsb-home-personalization .lsb-home-search-form .search-field { min-width: 76px; }',
    '#lsb-home-personalization[hidden] { display: none !important; }',
    '/* 主题首帖与评论建立清晰层级：首帖突出，评论缩进显示。 */',
    '/* 新版回复栏会作为列表的临时直接子节点插入；保持普通流，避免触发后续评论的网格自动排版。 */',
    '.topic-post-list { display: block; }',
    '.topic-post-list > .post-entry { box-sizing: border-box; }',
    '.topic-post-list > .post-entry:not([data-floor]) {',
    '  position: relative; margin: 0 0 14px; padding: 18px 20px !important;',
    '  border: 1px solid var(--line); border-left: 4px solid var(--brand);',
    '  border-radius: var(--radius); background: var(--panel) !important;',
    '  box-shadow: 0 10px 24px var(--shadow-base);',
    '}',
    '.topic-post-list > .post-entry:not([data-floor]) .post-head::before {',
    '  content: "楼主"; display: inline-flex; align-items: center; flex: 0 0 auto;',
    '  min-height: 20px; margin-right: 8px; padding: 0 7px; border-radius: 999px;',
    '  background: var(--brand-soft); color: var(--brand-hover); font-size: 11px; font-weight: 700;',
    '}',
    '.topic-post-list > .post-entry:not([data-floor]) .post-content {',
    '  margin-top: 14px; padding-top: 14px; border-top: 1px solid var(--line-soft);',
    '}',
    '.topic-post-list > .post-entry[data-floor] {',
    '  position: relative; grid-template-columns: 36px minmax(0, 1fr);',
    '  margin: 0 0 0 clamp(18px, 3vw, 42px); padding: 14px 0 !important; border: 0;',
    '  border-radius: 0; background: transparent !important; box-shadow: none;',
    '  transition: color .18s ease;',
    '}',
    '.topic-post-list > .post-entry[data-floor]::after {',
    '  content: ""; position: absolute; right: 0; bottom: 0; left: 0; height: 1px;',
    '  background: linear-gradient(90deg, var(--brand) 0, var(--brand) 28px, var(--line) 28px, var(--line-soft) 72%, transparent 100%);',
    '  opacity: .42; pointer-events: none; transition: opacity .18s ease;',
    '}',
    '.topic-post-list > .post-entry[data-floor]:hover {',
    '  background: transparent !important; box-shadow: none;',
    '}',
    '.topic-post-list > .post-entry[data-floor]:hover::after { opacity: .72; }',
    '.topic-post-list > .post-entry[data-floor]:last-child::after { display: none; }',
    '.topic-post-list > .post-entry[data-floor] .post-head::before {',
    '  content: "评论"; display: inline-flex; align-items: center; flex: 0 0 auto;',
    '  min-height: 19px; margin-right: 7px; padding: 0 6px; border: 1px solid var(--line);',
    '  border-radius: 999px; color: var(--text-subtle); font-size: 10px; font-weight: 700;',
    '}',
    '.topic-post-list > .post-entry[data-floor] .post-author { color: var(--text); font-weight: 700; }',
    '.topic-post-list > .post-entry[data-floor] .post-meta { margin-top: 5px; }',
    '.topic-post-list > .post-entry[data-floor] .post-content {',
    '  width: auto; margin: 0; padding: 0; border: 0; border-radius: 0; background: transparent;',
    '}',
    '.topic-post-list > .post-entry[data-floor] .post-head.has-floor { min-height: 30px; padding-right: 176px !important; }',
    '.topic-post-list > .post-entry[data-floor] .post-ops { gap: 6px; }',
    '.topic-post-list > .post-entry[data-floor] .icon-action { width: 30px; height: 30px; opacity: .7; }',
    '.topic-post-list > .post-entry[data-floor] .icon-action::before { width: 18px; height: 18px; background-size: 18px 18px; }',
    '.topic-post-list > .post-entry[data-floor] .icon-quote::before { -webkit-mask-size: 18px 18px; mask-size: 18px 18px; }',
    '.topic-post-list > .post-entry[data-floor] .content-report-icon { width: 18px; height: 18px; }',
    '.topic-post-list > .post-entry[data-floor] .like-coin-form .like-coin-action {',
    '  min-width: 30px; height: 30px; min-height: 30px; padding: 0 4px; gap: 3px; font-size: 13px; opacity: .7;',
    '}',
    '.topic-post-list > .post-entry[data-floor] .like-coin-icon { width: 18px; height: 18px; flex-basis: 18px; }',
    '.topic-post-list > .post-entry[data-floor] .post-floor {',
    '  order: initial; min-width: 30px; height: 30px; padding: 0 3px; border: 0; border-radius: 0;',
    '  background: transparent; color: var(--text-muted); font-size: 14px; font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '/* 发帖编辑器插件的浅色回退值改为跟随当前深色主题。 */',
    '.topic-type-group .topic-type-choice,',
    '.topic-type-panels > .topic-type-panel,',
    '.lottery-prize-row, .lottery-card, .lottery-condition {',
    '  background: var(--card-bg) !important; color: var(--text) !important;',
    '}',
    '.lottery-rule-note { background: var(--brand-soft) !important; color: var(--text-muted) !important; }',
    '.lottery-title-status, .lottery-result { background: var(--warning-soft) !important; color: var(--warning) !important; }',
    '.lottery-title-status.drawn {',
    '  background: var(--success-soft) !important; color: var(--success) !important;',
    '}',
    '.topic-type-group .topic-type-choice strong, .topic-type-group-title,',
    '.lottery-prize-head, .lottery-prize-row label, .lottery-card strong { color: var(--text) !important; }',
    '.topic-type-group .topic-type-choice small, .lottery-prize-row small, .lottery-card header span,',
    '.lottery-card header em, .lottery-prizes span, .virtual-card-tip { color: var(--text-muted) !important; }',
    '@media (max-width: 720px) {',
    '  .topic-post-list { gap: 0; }',
    '  .topic-post-list > .post-entry:not([data-floor]) { padding: 14px !important; }',
    '  .topic-post-list > .post-entry[data-floor] {',
    '    grid-template-columns: 32px minmax(0, 1fr); column-gap: 9px;',
    '    margin-left: 8px; padding: 12px 0 !important;',
    '  }',
    '  .topic-post-list > .post-entry[data-floor] .post-head.has-floor { padding-right: 168px !important; }',
    '}',
    '/* 每个标签独立圆角；四角统一封顶 12px，避免站点的首尾伪类把单个标签压成胶囊。 */',
    '.topic-toolbar > .tab-bar {',
    '  display: inline-flex !important; flex: 0 0 auto !important; align-items: stretch !important;',
    '  gap: 5px !important; width: max-content !important; max-width: 100% !important;',
    '  border-radius: 0 !important; overflow: visible !important;',
    '  isolation: auto !important; transform: none !important;',
    '}',
    '.topic-toolbar > .tab-bar > a.tab,',
    '.topic-toolbar > .tab-bar > a.tab:first-child,',
    '.topic-toolbar > .tab-bar > a.tab:last-child,',
    '.topic-toolbar > .tab-bar > a.tab:not(:has(~ .tab)),',
    '.topic-toolbar > .tab-bar > a.tab.active {',
    '  display: inline-flex !important; align-items: center !important; justify-content: center !important;',
    '  min-height: 27px !important; line-height: 1.1 !important; box-sizing: border-box !important;',
    '  border-radius: var(--lsb-tab-radius) !important;',
    '  border-top-left-radius: var(--lsb-tab-radius) !important;',
    '  border-top-right-radius: var(--lsb-tab-radius) !important;',
    '  border-bottom-right-radius: var(--lsb-tab-radius) !important;',
    '  border-bottom-left-radius: var(--lsb-tab-radius) !important;',
    '  margin-left: 0 !important; overflow: hidden !important; background-clip: padding-box !important;',
    '}',
    '.topic-toolbar > .tab-bar > a.tab + a.tab { margin-left: 0 !important; }',
    '/* 搜索框内部控件统一字号、留白和圆角。 */',
    '.search-form {',
    '  box-sizing: border-box; border-radius: var(--lsb-search-radius) !important; overflow: hidden;',
    '}',
    '.search-field {',
    '  flex: 0 0 82px !important; height: calc(100% - 8px) !important;',
    '  margin: 4px 0 4px 4px !important; padding: 0 28px 0 12px !important;',
    '  border: 1px solid var(--line-soft) !important;',
    '  border-radius: var(--lsb-search-radius) !important;',
    '  background-color: var(--panel) !important; color: var(--text) !important;',
    '  font-size: var(--lsb-base-font-size) !important; line-height: 1 !important;',
    '  appearance: none; -webkit-appearance: none;',
    '  background-image: url("data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 width=%2714%27 height=%2714%27 viewBox=%270 0 14 14%27 fill=%27none%27%3E%3Cpath d=%27M3.5 5.5 7 9l3.5-3.5%27 stroke=%27%237f7f7f%27 stroke-width=%271.4%27 stroke-linecap=%27round%27 stroke-linejoin=%27round%27/%3E%3C/svg%3E");',
    '  background-repeat: no-repeat; background-position: right 9px center; background-size: 14px;',
    '}',
    '.search-input { padding: 0 14px !important; font-size: var(--lsb-base-font-size) !important; }',
    '.search-btn { width: 48px !important; padding: 0 12px !important; display: inline-flex; align-items: center; justify-content: center; border-radius: 0 var(--lsb-search-radius) var(--lsb-search-radius) 0 !important; }',
    '.search-btn svg { width: 19px !important; height: 19px !important; }',
    '.search-field option { background: var(--panel); color: var(--text); }',
    '.search-form:has(.lsb-search-select) { overflow: visible !important; }',
    '.lsb-search-select { position: relative; flex: 0 0 88px; height: 100%; z-index: 3; }',
    '.lsb-search-native {',
    '  position: absolute !important; width: 1px !important; height: 1px !important;',
    '  opacity: 0 !important; pointer-events: none !important; clip: rect(0 0 0 0) !important;',
    '}',
    '.lsb-search-select-trigger {',
    '  position: relative; display: flex; align-items: center; width: 100%; height: 100%;',
    '  padding: 0 26px 0 12px; border: 0; border-right: 1px solid var(--line-soft);',
    '  border-radius: var(--lsb-search-radius) 0 0 var(--lsb-search-radius);',
    '  background: var(--panel); color: var(--text); font: inherit; font-size: var(--lsb-base-font-size);',
    '  text-align: left; cursor: pointer;',
    '}',
    '.lsb-search-select-trigger::after {',
    '  content: ""; position: absolute; right: 10px; top: 50%; width: 7px; height: 7px;',
    '  border-right: 1.5px solid currentColor; border-bottom: 1.5px solid currentColor;',
    '  opacity: .72; transform: translateY(-65%) rotate(45deg);',
    '}',
    '.lsb-search-select-trigger[aria-expanded="true"]::after { transform: translateY(-30%) rotate(225deg); }',
    '.lsb-search-options {',
    '  position: absolute; top: calc(100% + 6px); left: 0; width: 132px; padding: 5px;',
    '  border: 1px solid var(--line); border-radius: var(--lsb-search-radius);',
    '  background: var(--panel); box-shadow: 0 14px 34px var(--shadow-medium);',
    '}',
    '.lsb-search-options[hidden] { display: none !important; }',
    '.lsb-search-option {',
    '  display: block; width: 100%; min-height: 32px; padding: 6px 9px; border: 0;',
    '  border-radius: min(var(--radius-sm), 8px); background: transparent; color: var(--text-muted);',
    '  font: inherit; font-size: var(--lsb-base-font-size); text-align: left; cursor: pointer;',
    '}',
    '.lsb-search-option:hover, .lsb-search-option[aria-selected="true"] {',
    '  background: var(--brand-soft); color: var(--text);',
    '}',
    'html, body, .top, .card, .box, .home-shell, .main-panel, .sidebar-card {',
    '  transition: background-color .18s ease, border-color .18s ease, color .18s ease;',
    '}',
    '/* 自定义面板：保留原有交互结构，仅对排版和控件做轻量优化。 */',
    '#lsb-layout-toggle {',
    '  --lsb-ui-accent: var(--brand, #b8b8b8); --lsb-ui-text: var(--text, #eeeeee);',
    '  --lsb-ui-panel: var(--panel, #1b1b1b); --lsb-ui-line: var(--line, #343434);',
    '  position: fixed; left: 22px; bottom: 22px; z-index: 2147483646;',
    '  display: inline-flex; align-items: center; justify-content: center;',
    '  width: 44px; height: 44px; padding: 0; border: 1px solid var(--lsb-ui-line);',
    '  border-radius: 12px; background: var(--lsb-ui-panel); color: var(--lsb-ui-text);',
    '  box-shadow: 0 6px 18px var(--shadow-base, rgba(0,0,0,.28));',
    '  cursor: pointer; touch-action: none; transition: transform .18s ease, border-color .18s ease, background .18s ease;',
    '}',
    '#lsb-layout-toggle.lsb-toggle-dragging { cursor: grabbing; transform: none !important; transition: none !important; }',
    '#lsb-layout-toggle:hover { transform: scale(1.05); border-color: var(--lsb-ui-accent); background: var(--brand-soft, var(--lsb-ui-panel)); }',
    '#lsb-layout-toggle[aria-expanded="true"] { border-color: var(--lsb-ui-accent); background: var(--brand-soft, var(--lsb-ui-panel)); }',
    '#lsb-layout-toggle:focus-visible, #lsb-layout-panel :focus-visible { outline: 2px solid var(--lsb-ui-accent); outline-offset: 2px; }',
    '#lsb-layout-toggle svg { width: 20px; height: 20px; }',
    '#lsb-modal-backdrop {',
    '  position: fixed; inset: 0; z-index: 2147483646;',
    '  background: var(--backdrop, rgba(0,0,0,.55));',
    '}',
    '#lsb-modal-backdrop[hidden] { display: none !important; }',
    '#lsb-layout-panel {',
    '  --lsb-ui-accent: var(--brand, #b8b8b8); --lsb-ui-text: var(--text, #eeeeee);',
    '  --lsb-ui-panel: var(--panel, #1b1b1b); --lsb-ui-line: var(--line, #343434);',
    '  --lsb-ui-line-soft: var(--line-soft, #272727); --lsb-ui-muted: var(--text-muted, #b6b6b6);',
    '  position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);',
    '  z-index: 2147483647;',
    '  width: min(560px, calc(100vw - 32px)); max-height: calc(100vh - 64px);',
    '  display: flex; flex-direction: column; overflow: hidden;',
    '  color: var(--lsb-ui-text); background: var(--lsb-ui-panel);',
    '  border: 1px solid var(--lsb-ui-line); border-radius: 14px;',
    '  box-shadow: 0 18px 46px var(--shadow-medium, rgba(0,0,0,.48));',
    '  font: 13px/1.45 -apple-system, BlinkMacSystemFont, "PingFang SC", "Microsoft YaHei", sans-serif;',
    '  scrollbar-color: var(--lsb-ui-muted) transparent;',
    '}',
    '#lsb-layout-panel[hidden] { display: none !important; }',
    '/* 侧栏对调：仅切换按钮位置联动 */',
    '.lsb-toggle-left { left: 22px !important; right: auto !important; }',
    '.lsb-toggle-right { right: 22px !important; left: auto !important; }',
    '.lsb-panel-head {',
    '  flex: 0 0 auto; display: flex; align-items: center;',
    '  justify-content: space-between; gap: 7px; padding: 15px 16px 13px;',
    '  border-bottom: 1px solid var(--lsb-ui-line); background: var(--lsb-ui-panel);',
    '  user-select: none;',
    '}',
    '.lsb-panel-head button { cursor: pointer; }',
    '.lsb-panel-title { display: grid; gap: 2px; }',
    '.lsb-panel-title strong { color: var(--lsb-ui-text); font-size: 15px; letter-spacing: .01em; }',
    '.lsb-panel-title span { color: var(--lsb-ui-muted); font-size: 11px; }',
    '.lsb-tabs {',
    '  flex: 0 0 auto; display: flex; gap: 4px; padding: 10px 16px 0;',
    '  border-bottom: 1px solid var(--lsb-ui-line); overflow-x: auto;',
    '}',
    '.lsb-tab {',
    '  flex: 1 1 0; min-height: 34px; padding: 0 10px;',
    '  border: 1px solid transparent; border-bottom: 0; border-radius: 8px 8px 0 0;',
    '  background: transparent; color: var(--lsb-ui-muted);',
    '  font: inherit; font-size: 12px; font-weight: 600; cursor: pointer; white-space: nowrap;',
    '}',
    '.lsb-tab:hover { color: var(--lsb-ui-text); background: var(--bg-soft, var(--lsb-ui-panel)); }',
    '.lsb-tab.lsb-tab-active { color: var(--lsb-ui-accent); border-color: var(--lsb-ui-line); background: var(--lsb-ui-panel); }',
    '.lsb-tab-panel { display: grid; gap: 17px; }',
    '.lsb-tab-panel[hidden] { display: none !important; }',
    '.lsb-panel-body { padding: 15px 16px 17px; overflow-y: auto; }',
    '.lsb-icon-button {',
    '  display: inline-flex; align-items: center; justify-content: center;',
    '  width: 22px; height: 22px; padding: 0; border: 0;',
    '  border-radius: 0; background: transparent; color: var(--lsb-ui-muted); font-size: 16px; line-height: 1; cursor: pointer;',
    '}',
    '.lsb-panel-credit { color: var(--lsb-ui-muted); font-size: 10px; line-height: 1; opacity: .72; white-space: nowrap; }',
    '.lsb-panel-credit a { color: inherit; text-decoration: none; }',
    '.lsb-section { display: grid; gap: 11px; }',
    '.lsb-section-title {',
    '  display: flex; align-items: center; gap: 8px; margin: 0;',
    '  color: var(--lsb-ui-muted); font-size: 10px; line-height: 1.2; font-weight: 700;',
    '  letter-spacing: .1em; text-transform: uppercase;',
    '}',
    '.lsb-section-title::after { content: ""; height: 1px; flex: 1; background: var(--lsb-ui-line-soft); }',
    '.lsb-range-row { display: grid; gap: 7px; }',
    '.lsb-range-head { display: flex; align-items: center; justify-content: space-between; gap: 12px; }',
    '.lsb-range-label, .lsb-field > span { color: var(--lsb-ui-muted); font-size: 12px; }',
    '.lsb-range-value { min-width: 54px; color: var(--lsb-ui-text); font-size: 12px; font-variant-numeric: tabular-nums; text-align: right; }',
    '.lsb-range { width: 100%; height: 18px; margin: 0; accent-color: var(--lsb-ui-accent); cursor: pointer; }',
    '.lsb-field { display: grid; gap: 7px; }',
    '.lsb-select, .lsb-textarea {',
    '  width: 100%; border: 1px solid var(--lsb-ui-line); border-radius: 8px;',
    '  background: var(--bg-soft, var(--lsb-ui-panel)); color: var(--lsb-ui-text); font: inherit; box-sizing: border-box;',
    '}',
    '.lsb-select { height: 38px; padding: 0 10px; cursor: pointer; }',
    '.lsb-select option { background: var(--lsb-ui-panel); color: var(--lsb-ui-text); }',
    '.lsb-select:focus, .lsb-textarea:focus { outline: none; border-color: var(--lsb-ui-accent); box-shadow: 0 0 0 2px var(--focus-ring, rgba(184,184,184,.34)); }',
    '.lsb-color-line {',
    '  display: grid; grid-template-columns: 42px 1fr; align-items: center; gap: 10px;',
    '  padding: 7px 9px; border: 1px solid var(--lsb-ui-line); border-radius: 9px; background: var(--bg-soft, var(--lsb-ui-panel));',
    '}',
    '.lsb-color-input { width: 42px; height: 30px; padding: 2px; border: 0; border-radius: 7px; background: transparent; cursor: pointer; }',
    '.lsb-color-value { color: var(--lsb-ui-muted); font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }',
    '.lsb-check-line { display: grid; grid-template-columns: 34px minmax(0, 1fr); align-items: center; gap: 10px; min-height: 26px; color: var(--lsb-ui-muted); cursor: pointer; }',
    '.lsb-check-line input { position: relative; width: 34px; height: 19px; margin: 0; border: 1px solid var(--lsb-ui-line); border-radius: 999px; background: var(--lsb-ui-line-soft); cursor: pointer; appearance: none; -webkit-appearance: none; transition: background-color .16s ease, border-color .16s ease; }',
    '.lsb-check-line input::after { content: ""; position: absolute; top: 3px; left: 3px; width: 11px; height: 11px; border-radius: 50%; background: var(--lsb-ui-muted); transition: left .16s ease, background-color .16s ease; }',
    '.lsb-check-line input:checked { border-color: var(--lsb-ui-accent); background: var(--lsb-ui-accent); }',
    '.lsb-check-line input:checked::after { left: 18px; background: var(--inverse, #111111); }',
    '.lsb-check-line input:focus-visible { outline: 2px solid var(--lsb-ui-accent); outline-offset: 2px; }',
    '.lsb-check-line input:checked + span { color: var(--lsb-ui-text); }',
    '.lsb-check-line span { line-height: 1.45; }',
    '.lsb-theme-note { margin: 0; color: var(--lsb-ui-muted); font-size: 11px; line-height: 1.55; }',
    '.lsb-filter-section { margin-top: 3px; }',
    '.lsb-actions { display: grid; grid-template-columns: 1fr 1fr; gap: 9px; }',
    '.lsb-button {',
    '  min-height: 38px; padding: 0 12px; border: 1px solid var(--lsb-ui-line); border-radius: 9px;',
    '  background: transparent; color: var(--lsb-ui-text); font: inherit; font-weight: 600; cursor: pointer;',
    '}',
    '.lsb-button:hover { border-color: var(--lsb-ui-accent); background: var(--brand-soft, transparent); }',
    '.lsb-button-primary { border-color: var(--lsb-ui-accent); background: var(--brand-soft, transparent); }',
    '.lsb-status { min-height: 16px; margin: 0; color: var(--lsb-ui-muted); font-size: 11px; text-align: center; }',
    '.lsb-input { width: 100%; height: 38px; padding: 0 10px; border: 1px solid var(--lsb-ui-line); border-radius: 8px; background: var(--bg-soft, var(--lsb-ui-panel)); color: var(--lsb-ui-text); font: inherit; box-sizing: border-box; }',
    '.lsb-input:focus { outline: none; border-color: var(--lsb-ui-accent); box-shadow: 0 0 0 2px var(--focus-ring, rgba(184,184,184,.34)); }',
    '.lsb-check-line-row { display: flex; align-items: center; justify-content: space-between; gap: 10px; }',
    '.lsb-upload-settings-toggle { display: inline-flex; align-items: center; justify-content: center; min-height: 24px; padding: 0 8px; border: 1px solid var(--lsb-ui-line); border-radius: 6px; background: transparent; color: var(--lsb-ui-muted); font: 10px/1 inherit; cursor: pointer; }',
    '.lsb-upload-settings-toggle:hover { border-color: var(--lsb-ui-accent); color: var(--lsb-ui-text); }',
    '.lsb-upload-settings-toggle[hidden], .lsb-upload-settings[hidden] { display: none !important; }',
    '.lsb-upload-settings { display: grid; gap: 10px; margin: 4px 0 2px; padding: 0; }',
    '.lsb-upload-profiles-head { display: grid; gap: 3px; }',
    '.lsb-upload-profiles-tip { margin: 0; color: var(--lsb-ui-muted); font-size: 10px; line-height: 1.5; }',
    '.lsb-upload-profiles { display: grid; gap: 6px; }',
    '.lsb-upload-profile-item { display: flex; align-items: center; gap: 8px; padding: 9px 10px; border: 1px solid var(--lsb-ui-line); border-radius: 9px; background: var(--bg-soft, var(--lsb-ui-panel)); cursor: grab; }',
    '.lsb-upload-profile-item:active { cursor: grabbing; }',
    '.lsb-upload-profile-item:hover { border-color: var(--lsb-ui-accent); }',
    '.lsb-upload-profile-item:focus-visible { outline: 2px solid var(--lsb-ui-accent); outline-offset: -1px; }',
    '.lsb-upload-profile-item.lsb-upload-profile-dragging { opacity: .5; border-style: dashed; }',
    '.lsb-upload-profile-name { flex: 1 1 auto; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: var(--lsb-ui-text); font-size: 12px; font-weight: 600; }',
    '.lsb-upload-profile-meta { flex: 0 0 auto; color: var(--lsb-ui-muted); font-size: 10px; font-variant-numeric: tabular-nums; }',
    '.lsb-upload-profile-add { width: 100%; border-style: dashed !important; }',
    '.lsb-upload-editor { position: absolute; inset: 0; z-index: 20; display: flex; flex-direction: column; background: var(--lsb-ui-panel); }',
    '.lsb-upload-editor[hidden] { display: none !important; }',
    '.lsb-upload-editor .lsb-panel-body { flex: 1 1 auto; min-height: 0; }',
    '.lsb-upload-editor-actions { flex: 0 0 auto; display: flex; gap: 9px; padding: 12px 16px; border-top: 1px solid var(--lsb-ui-line); }',
    '.lsb-upload-editor-actions .lsb-button { flex: 1 1 0; }',
    '.lsb-upload-group { display: grid; gap: 9px; padding: 11px 12px; border: 1px solid var(--lsb-ui-line); border-radius: 10px; background: var(--bg-soft, var(--lsb-ui-panel)); }',
    '.lsb-upload-group-title { margin: 0; color: var(--lsb-ui-muted); font-size: 10px; line-height: 1.2; font-weight: 700; letter-spacing: .1em; text-transform: uppercase; }',
    '.lsb-form-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }',
    '.lsb-form-grid .lsb-field-wide { grid-column: 1 / -1; }',
    '.lsb-upload-hint { margin: 0; color: var(--lsb-ui-muted); font-size: 10px; line-height: 1.5; }',
    '.lsb-image-upload-button { display: inline-flex; align-items: center; justify-content: center; min-height: 28px; margin: 7px 0 0; padding: 0 9px; border: 1px dashed var(--line, #343434); border-radius: 7px; background: transparent; color: var(--text-muted, #b6b6b6); font: 12px/1 inherit; cursor: pointer; }',
    '.lsb-image-upload-button:hover, .lsb-image-upload-button:focus-visible { border-color: var(--brand, #b8b8b8); color: var(--text, #eeeeee); outline: none; }',
    '.lsb-image-upload-button[disabled] { opacity: .65; cursor: wait; }',
    '/* 仅重排正式回复区的上传与提交行：不移动 DOM，不影响上传、附件或回复事件。 */',
    '@supports selector(.ajax-reply-form:has(.lsb-image-upload-button)) {',
    '  .reply-panel .ajax-reply-form:has(.lsb-image-upload-button) {',
    '    display: grid !important; grid-template-columns: minmax(0, 1fr) auto auto !important;',
    '    grid-template-rows: auto auto minmax(118px, auto) auto !important;',
    '    grid-template-areas: "lsb-reply-label lsb-reply-label lsb-reply-label" "lsb-reply-toolbar lsb-reply-toolbar lsb-reply-toolbar" "lsb-reply-content lsb-reply-content lsb-reply-content" "lsb-reply-attachment lsb-reply-upload lsb-reply-actions" !important;',
    '    align-items: center !important; column-gap: 10px !important; row-gap: 10px !important;',
    '  }',
    '  .reply-panel .ajax-reply-form:has(.lsb-image-upload-button) > .nb-editor-field { display: contents !important; }',
    '  .reply-panel .ajax-reply-form:has(.lsb-image-upload-button) > .nb-editor-field .grid > span:first-child { grid-area: lsb-reply-label; }',
    '  .reply-panel .ajax-reply-form:has(.lsb-image-upload-button) > .nb-editor-field > .nb-editor { grid-area: lsb-reply-toolbar; }',
    '  .reply-panel .ajax-reply-form:has(.lsb-image-upload-button) > .nb-editor-field textarea { grid-area: lsb-reply-content; }',
    '  .reply-panel .ajax-reply-form:has(.lsb-image-upload-button) > .nb-editor-field .lsb-image-upload-button {',
    '    grid-area: lsb-reply-upload; margin: 0 !important; white-space: nowrap;',
    '  }',
    '  .reply-panel .ajax-reply-form:has(.lsb-image-upload-button) > .nb-editor-field :is(input[type="file"], .attachment, .attachment-hint, .attachment-tip, .attachment-help, .attachment-control, [data-attachment], [class*="attachment"]) {',
    '    grid-area: lsb-reply-attachment; min-width: 0; align-self: center; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;',
    '  }',
    '  .reply-panel .ajax-reply-form:has(.lsb-image-upload-button) > .quick-reply-actions {',
    '    grid-area: lsb-reply-actions; margin: 0 !important; align-self: center !important; white-space: nowrap;',
    '  }',
    '}',
    '.lsb-image-upload-drop-target { outline: 2px dashed var(--brand, #b8b8b8); outline-offset: 3px; }',
    '.lsb-image-upload-hint { margin: 5px 0 0; color: var(--text-muted, #b6b6b6); font-size: 11px; }',
    '#lsb-image-lightbox { position: fixed; inset: 0; z-index: 2147483645; display: flex; align-items: center; justify-content: center; padding: 24px; background: var(--backdrop, rgba(0,0,0,.68)); cursor: zoom-out; }',
    '#lsb-image-lightbox[hidden] { display: none !important; }',
    '#lsb-image-lightbox .lsb-lightbox-image { max-width: min(1200px, 100%); max-height: calc(100vh - 48px); border: 1px solid var(--line, #343434); border-radius: var(--radius, 6px); background: var(--panel, #1b1b1b); box-shadow: 0 20px 52px var(--shadow-medium, rgba(0,0,0,.48)); cursor: default; object-fit: contain; }',
    '#lsb-image-lightbox .lsb-lightbox-close { position: absolute; top: 14px; right: 16px; width: 30px; height: 30px; padding: 0; border: 1px solid var(--line, #343434); border-radius: 8px; background: var(--panel, #1b1b1b); color: var(--text, #eeeeee); font-size: 20px; line-height: 1; cursor: pointer; }',
    '.post-entry .post-content img[data-lsb-lightbox-image], .post-item .post-content img[data-lsb-lightbox-image] { cursor: zoom-in; }',
    '/* 首页身份、UID 与头像资料卡：仅使用脚本私有类，避免覆盖站点现有组件。 */',
    '.post-item .lsb-author-enhancement { --lsb-marker-color: var(--brand, #5eaaa0); display: inline-flex; align-items: center; gap: 4px; margin-left: 6px; vertical-align: middle; white-space: nowrap; font-variant-numeric: tabular-nums; }',
    '.post-item .lsb-author-enhancement[data-lsb-identity="creator"] { --lsb-marker-color: var(--brand, #5eaaa0); }',
    '.post-item .lsb-author-enhancement[data-lsb-identity="aiRobot"] { --lsb-marker-color: var(--info, #8fafd0); }',
    '.post-item .lsb-author-enhancement[data-lsb-identity="communityHost"] { --lsb-marker-color: var(--success, #8bb59b); }',
    '.post-item .lsb-identity-badge, .post-item .lsb-uid-badge { display: inline-flex; align-items: center; min-height: 18px; box-sizing: border-box; border: 1px solid color-mix(in srgb, var(--lsb-marker-color) 52%, var(--line, #343434)); border-radius: 999px; line-height: 1; }',
    '.post-item .lsb-identity-badge { padding: 0 6px; background: color-mix(in srgb, var(--lsb-marker-color) 16%, transparent); color: var(--lsb-marker-color); font-size: 10px; font-weight: 700; letter-spacing: .02em; }',
    '.post-item .lsb-uid-badge { padding: 0 5px; background: transparent; color: color-mix(in srgb, var(--lsb-marker-color) 78%, var(--text-muted, #b6b6b6)); font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 10px; font-weight: 600; }',
    '#lsb-home-profile-card { position: fixed; z-index: 2147483644; width: min(292px, calc(100vw - 24px)); padding: 13px; border: 1px solid var(--line, #343434); border-radius: min(var(--radius, 6px), 12px); background: var(--panel, #1b1b1b); color: var(--text, #eeeeee); box-shadow: 0 16px 36px var(--shadow-medium, rgba(0,0,0,.48)); pointer-events: none; opacity: 0; transform: translateY(4px); transition: opacity .14s ease, transform .14s ease; font: 12px/1.45 -apple-system, BlinkMacSystemFont, "PingFang SC", "Microsoft YaHei", sans-serif; }',
    '#lsb-home-profile-card[hidden] { display: none !important; }',
    '#lsb-home-profile-card.lsb-visible { opacity: 1; transform: translateY(0); }',
    '#lsb-home-profile-card .lsb-profile-card-head { display: flex; align-items: center; gap: 9px; padding-bottom: 10px; border-bottom: 1px solid var(--line-soft, #272727); }',
    '#lsb-home-profile-card .lsb-profile-card-avatar { width: 34px; height: 34px; flex: 0 0 34px; border: 1px solid var(--line, #343434); border-radius: 50%; background: var(--bg, #121212); object-fit: cover; }',
    '#lsb-home-profile-card .lsb-profile-card-name { overflow: hidden; color: var(--text, #eeeeee); font-size: 13px; font-weight: 700; text-overflow: ellipsis; white-space: nowrap; }',
    '#lsb-home-profile-card .lsb-profile-card-uid { margin-top: 1px; color: var(--text-subtle, #898989); font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 10px; font-variant-numeric: tabular-nums; }',
    '#lsb-home-profile-card .lsb-profile-card-grid { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); gap: 7px 12px; margin: 11px 0 0; }',
    '#lsb-home-profile-card .lsb-profile-card-item { display: grid; gap: 1px; min-width: 0; }',
    '#lsb-home-profile-card .lsb-profile-card-item dt { margin: 0; color: var(--text-subtle, #898989); font-size: 10px; }',
    '#lsb-home-profile-card .lsb-profile-card-item dd { position: relative; overflow: hidden; margin: 0; color: var(--text-muted, #b6b6b6); font-size: 11px; white-space: nowrap; font-variant-numeric: tabular-nums; }',
    '#lsb-home-profile-card .lsb-profile-card-value { display: inline-block; min-width: 100%; }',
    '#lsb-home-profile-card .lsb-profile-card-item dd.lsb-profile-card-overflow .lsb-profile-card-value { min-width: max-content; padding-right: 24px; animation: lsb-profile-card-marquee var(--lsb-marquee-duration, 18s) ease-in-out infinite alternate; animation-delay: 1.6s; }',
    '@keyframes lsb-profile-card-marquee { 0%, 14% { transform: translateX(0); } 86%, 100% { transform: translateX(var(--lsb-marquee-offset, 0px)); } }',
    '@media (prefers-reduced-motion: reduce) { #lsb-home-profile-card .lsb-profile-card-item dd.lsb-profile-card-overflow { overflow: visible; white-space: normal; overflow-wrap: anywhere; } #lsb-home-profile-card .lsb-profile-card-item dd.lsb-profile-card-overflow .lsb-profile-card-value { min-width: 0; padding-right: 0; animation: none; } }',
    '#lsb-home-profile-card[data-loading="true"] .lsb-profile-card-item dd { color: var(--text-subtle, #898989); }',
    'body.lsb-lightbox-open { overflow: hidden !important; }',
    '@media (max-width: 520px) {',
    '  #lsb-layout-toggle { right: 12px; bottom: 12px; }',
    '  #lsb-layout-panel { width: calc(100vw - 24px); }',
    '}',
    '@media (prefers-reduced-motion: reduce) {',
    '  #lsb-layout-toggle, html, body, .top, .card, .box, .home-shell, .main-panel, .sidebar-card { transition-duration: .01ms !important; }',
    '}',
    '.lsb-textarea { padding: 8px 10px; font-size: 12px; line-height: 1.5; resize: vertical; }'
].join('\n');

// 更新检测常量：脚本发布在用户的 static 仓库，pub 为标准版、perv 为预览版
export const STATIC_BASE_URL = 'https://static.yaoonion.fun/lsb';
export const UPDATE_VERSION_FILE = 'version.json';
export const UPDATE_SCRIPT_FILE = 'linux-sb-enhance.user.js';
export const LOCAL_STORAGE_LAST_CHECK_TIME = 'lsbLastUpdateCheck';
export const UPDATE_CHECK_INTERVAL = 24 * 60 * 60 * 1000; // 24 小时
export const PREVIEW_UPDATE_CHECK_INTERVAL = 60 * 60 * 1000; // 1 小时
